name: nbrsync
title: nbRsync
base: core24
version: 'REPLACE_WITH_VERSION'
summary: rsync GUI with an integrated scheduler, and a CLI
description: |
    nbRsync is a GUI for rsync that simplifies synchronization of files and directories while preserving the details of the rsync options.

    nbRsync works with the concept of Jobs and Tasks. Jobs can contain zero or more Tasks and Tasks can belong to zero or more Jobs.

    It is possible to execute commands before and after jobs and tasks.

    nbRsync also comes with a built-in scheduler, a scheduler that has to be started from the command line.

    _Make sure to backup your data before using nbRsync_ 🙃
grade: stable
platforms:
    amd64:
confinement: classic
icon: snap/gui/nbrsync.png
license: Apache-2.0
compression: lzo

source-code:
  - https://github.com/trixon/nbrsync
contact:
  - patrik@trixon.se
website:
  - https://trixon.se
issues:
  - https://github.com/trixon/nbrsync/issues
donation:
  - https://buymeacoffee.com/trixon

apps:
  nbrsync:
    command: nbrsync/bin/nbrsync

parts:
  nbrsync:
    plugin: dump
    #source: https://github.com/trixon/nbrsync/releases/download/v$SNAPCRAFT_PROJECT_VERSION/nbrsync-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source: /root/project/nbrsync-$SNAPCRAFT_PROJECT_VERSION-linux.zip
    source-type: zip
    stage-packages:
      - rsync

  config:
    after: [nbrsync]
    plugin: nil
    override-prime: |
      craftctl default
      sed -i 's/${HOME}\/.${APPNAME}/${SNAP_USER_COMMON}\/.nbrsync/' /root/prime/nbrsync/bin/nbrsync
      sed -i 's/${HOME}\/.cache\/${APPNAME}/${SNAP_USER_COMMON}\/.cache\/nbrsync/' /root/prime/nbrsync/bin/nbrsync
      
lint:
  ignore: [library]
